export const PATH = {
  HOME: '/',
  SHOP: '/shop',
  PRESCRIPTION: '/prescription',
  ONLINE_PHARMACIST: '/online-pharmacist',
  HELP_AND_SUPPORT: '/help-and-support',
  CONTACT: '/contact',
  LOGIN: '/login',
  SIGNUP: '/signup',
  OTP: '/otp',
  RESET_PASSWORD: '/reset-password',
  CONFIRM_PASSWORD: '/confirm-password',
  CATEGORY: '/category',
  PRODUCT: '/product',
  SEARCH: '/search',
  CART: '/cart',
  DELIVERY_INFO: '/delivery-info',
  SHIPPING_INFO: '/shipping-info',
  ORDER_SUCCESS: '/order-success',
};
