export const data = [
    {
        id: '#AHGA68',
        product: 'Strepsils',
        date: '28/09/2023',
        customer: 'John Doe',
        status: 'pending',
        amount: '500',
    },
    {
        id: '#AHGA68',
        product: 'Strepsils',
        date: '28/09/2023',
        customer: 'John Doe',
        status: 'delivered',
        amount: '500',
    },
    {
        id: '#AHGA68',
        product: 'Strepsils',
        date: '28/09/2023',
        customer: 'John Doe',
        status: 'pending',
        amount: '500',
    },
    {
        id: '#AHGA68',
        product: 'Strepsils',
        date: '28/09/2023',
        customer: 'John Doe',
        status: 'cancelled',
        amount: '500',
    },
    {
        id: '#AHGA68',
        product: 'Strepsils',
        date: '28/09/2023',
        customer: 'John Doe',
        status: 'pending',
        amount: '500',
    },
    {
        id: '#AHGA68',
        product: 'Strepsils',
        date: '28/09/2023',
        customer: 'John Doe',
        status: 'delivered',
        amount: '500',
    },
    {
        id: '#AHGA68',
        product: 'Strepsils',
        date: '28/09/2023',
        customer: 'John Doe',
        status: 'pending',
        amount: '500',
    },
    {
        id: '#AHGA68',
        product: 'Strepsils',
        date: '28/09/2023',
        customer: 'John Doe',
        status: 'cancelled',
        amount: '500',
    }
]